/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:9f440708-d856-4773-bc1d-890fbf9074f8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_3p8KwBAlC",
    "aws_user_pools_web_client_id": "58ma2r5n0qjsqnesu0os98htt9",
    "oauth": {}
};


export default awsmobile;
